version: "3"
services:
  switch-bot-flask-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:8080", "app:app"]
    networks:
      - switch-bot-flask-api-network

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - switch-bot-flask-api
    networks:
      - switch-bot-flask-api-network

networks:
  switch-bot-flask-api-network:
    driver: bridge